# Generated by Django 4.1.7 on 2023-09-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_remove_product_subcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="subcategory",
            field=models.CharField(default="", max_length=50),
        ),
    ]
