# Generated by Django 4.1.7 on 2023-10-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_orders_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product", name="desc", field=models.CharField(max_length=1000),
        ),
    ]
